/**
 * Fetch Playlist Constants
 */
export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST'
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS'
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR'

/**
 * Fetch Track Constants
 */
export const FETCH_TRACK_REQUEST = 'FFETCH_TRACK_REQUEST'
export const FETCH_TRACK_SUCCESS = 'FETCH_TRACK_SUCCESS'
export const FETCH_TRACK_ERROR = 'FETCH_TRACK_ERROR'